<?php

namespace NaxCrmBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * AclRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclRolesRepository extends AbstractEntityRepository
{
    public function getList($params)
    {
        $filters = [];
        $order = [];
        if (isset($params['filters'])) $filters = $params['filters'];
        if (isset($params['order'])) $order = $params['order'];

        $qb = $this->createQueryBuilder('r')
            ->select('COUNT(r.id)');
        $total = $qb->getQuery()->getSingleScalarResult();

        $filters_array = [
            'id'          => ['type' => 'integer',   'table' => 'r'],
            'name'        => ['type' => 'string',    'table' => 'r'],
            'description' => ['type' => 'string',    'table' => 'r'],
            'created'     => ['type' => 'daterange', 'table' => 'r'],
        ];


        //apply filters
        $this->buildFilters($filters_array, $filters, $qb);

        $qb->select('COUNT(r.id) filtered');
        $filteredData = $qb->getQuery()->getScalarResult();
        $filteredData = array_shift($filteredData);
        $filtered = $filteredData['filtered'];

        $this->setPagination($params, $qb);

        $qb->select(
            'r.id',
            'r.name',
            'r.description',
            "DATE_FORMAT(r.created, '%Y-%m-%d %H:%i:%s') created"
        );

        $this->setOrder($order, $filters_array, $qb);

        $data = $qb->getQuery()->getResult();

        return [
            'total'     => (int) $total,
            'filtered'  => (int) $filtered,
            'filters'   => $this->genFilters($filters_array),
            'rows'      => $data,
        ];
    }
}
