<?php

namespace NaxCrmBundle\Repository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenGroupRepository extends AbstractEntityRepository
{
}
